### PR TITLE
Fixed docker config.

### PR DESCRIPTION
**Pull request by b-solution**
Hi @jldroid19 , I hope you are well. The issue was not with Firebase; it was with Docker. We did not configure it properly, but I have fixed the Docker configuration. You can check this PR. I have added a new shell file called build-forever.sh. You can run it in production mode by passing the 'production' parameter like this: ./build-forever.sh production. By default, it will automatically run my compose-dev.yml file. Now Firebase is responding well.#73.

### CODE REVIEW

**Comment by jldroid19** [comment]
@b-solution thank you for this. I'll test this locally and get back to you on it. The concern I have is the production application is not deployed using docker-compose. It is deployed to a container service. So that means the image is being kept in a registry. I'll try building the container locally using your recommendations and see if that image can be distributed and used across different environments. Thanks!

**Comment by b-solution** [comment]
Sure @jldroid19 . When you test let me know. I'll be working on pending tickets you send me on email. Thanks!

**Comment by jldroid19** [comment]
@b-solution this did not fix the connectivity to the Firebase database. I agree this is a container issue. However, we are going to keep this running in a traditional way using pm2 for production.

**Comment by jldroid19** [comment]
@b-solution I had to adjust some things on my local to get the production build to work. This is great, was this due to env vars not being passed correctly?

**Pull request merged**
